import{a as h,S as g,i as a}from"./assets/vendor-DvfmeZXB.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))r(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function s(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(o){if(o.ep)return;o.ep=!0;const n=s(o);fetch(o.href,n)}})();const L="53497690-592ac66f2c7c0c491717e710e",y=async(e,t)=>{const s=`https://pixabay.com/api/?key=${L}&q=${encodeURIComponent(e)}&page=${t}&per_page=15&image_type=photo&orientation=horizontal&safesearch=true`;return(await h.get(s)).data},w=new g(".gallery a"),m=e=>{const t=document.querySelector(".gallery"),s=e.map(r=>`
        <li>
            <a href="${r.largeImageURL}">
                <img src="${r.webformatURL}" alt="${r.tags}" />
            </a>
            <ul class="description">
                <li><span>Likes:</span> ${r.likes}</li>
                <li><span>Views:</span> ${r.views}</li>
                <li><span>Comments:</span> ${r.comments}</li>
                <li><span>Downloads:</span> ${r.downloads}</li>
            </ul>
        </li>
    `).join("");t.insertAdjacentHTML("beforeend",s),w.refresh()},S=()=>{const e=document.querySelector(".gallery");e.innerHTML=""},p=()=>{document.querySelector(".loader").classList.remove("hidden")},c=()=>{document.querySelector(".loader").classList.add("hidden")},b=()=>{document.querySelector('button[type="button"').classList.remove("hidden")},u=()=>{document.querySelector('button[type="button"').classList.add("hidden")},f=document.querySelector(".form"),q=f.querySelector('input[name="search-text"]'),v=document.querySelector('button[type="button"]');c();u();let l=1,d="";v.addEventListener("click",async()=>{l+=1,p();try{const e=await y(d,l);m(e.hits);const t=document.querySelector(".gallery > li");if(document.querySelectorAll(".gallery > li").length>=e.totalHits&&(u(),a.info({message:"We're sorry, but you've reached the end of search results."})),t){const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,left:0,behavior:"smooth"})}}catch(e){console.error(e),a.error({message:"Something went wrong, please try again later!"})}finally{c()}});f.addEventListener("submit",async e=>{e.preventDefault(),u();const t=q.value.trim();if(d!==t&&(l=1),!t){a.warning({message:"Please enter a search term!"});return}S(),p();try{d=t;const s=await y(t,l);if(!s.hits||s.hits.length===0){a.info({message:"Sorry, no images found. Try another search!"}),c();return}m(s.hits),l+=1,document.querySelectorAll(".gallery > li").length<s.totalHits&&b()}catch(s){console.error(s),a.error({message:"Something went wrong, please try again later!"})}finally{c()}});
//# sourceMappingURL=index.js.map
