import{a as h,S as g,i as l}from"./assets/vendor-DvfmeZXB.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(r){if(r.ep)return;r.ep=!0;const n=s(r);fetch(r.href,n)}})();const L="53497690-592ac66f2c7c0c491717e710e",y=(e,t)=>{const s=`https://pixabay.com/api/?key=${L}&q=${encodeURIComponent(e)}&page=${t}&per_page=15&image_type=photo&orientation=horizontal&safesearch=true`;return h.get(s).then(o=>o.data)},b=new g(".gallery a"),m=e=>{const t=document.querySelector(".gallery"),s=e.map(o=>`
        <li>
            <a href="${o.largeImageURL}">
                <img src="${o.webformatURL}" alt="${o.tags}" />
            </a>
            <ul class="description">
                <li><span>Likes:</span> ${o.likes}</li>
                <li><span>Views:</span> ${o.views}</li>
                <li><span>Comments:</span> ${o.comments}</li>
                <li><span>Downloads:</span> ${o.downloads}</li>
            </ul>
        </li>
    `).join("");t.insertAdjacentHTML("beforeend",s),b.refresh()},S=()=>{const e=document.querySelector(".gallery");e.innerHTML=""},p=()=>{document.querySelector(".loader").classList.remove("hidden")},d=()=>{document.querySelector(".loader").classList.add("hidden")},w=()=>{document.querySelector('button[type="button"').classList.remove("hidden")},u=()=>{document.querySelector('button[type="button"').classList.add("hidden")},f=document.querySelector(".form"),q=f.querySelector('input[name="search-text"]'),v=document.querySelector('button[type="button"]');d();u();let a=1,c="";v.addEventListener("click",async()=>{p();const e=await y(c,a);m(e.hits),a+=1;const t=document.querySelector(".gallery > li");if(document.querySelectorAll(".gallery > li").length>=e.totalHits&&(u(),l.info({message:"We're sorry, but you've reached the end of search results."})),t){const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,left:0,behavior:"smooth"})}d()});f.addEventListener("submit",async e=>{e.preventDefault(),u();const t=q.value.trim();if(c!==t&&(a=1),!t){l.warning({message:"Please enter a search term!"});return}S(),p();try{const s=await y(t,a);if(!s.hits||s.hits.length===0){l.info({message:"Sorry, no images found. Try another search!"});return}m(s.hits),a+=1,c=t,document.querySelectorAll(".gallery > li").length<s.totalHits&&w()}catch(s){console.error(s),l.error({message:"Something went wrong, please try again later!"})}finally{d()}});
//# sourceMappingURL=index.js.map
